package Supermercado;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import myExceptions.ObjectNotFoundException;


public class Grafica1 extends javax.swing.JInternalFrame{
private Almacen almacen;
private Compra compra;
private Producto producto;
    /**
     * Creates new form Supermercado
     */
    public Grafica1(Almacen almacen) {
      this.almacen = almacen;
      this.compra = new Compra(null);
        initComponents();
       // this.informacion1.setModel(new SaleTableModel()); es lo mismo que  abajo.
        BuscarCliente buscar = new BuscarCliente();
        buscar1.addActionListener(buscar);
        BuscarProducto buscarP = new BuscarProducto();
        codigo1.addActionListener(buscarP);
        SaleTableModel tabla = new SaleTableModel();
        informacion1.setModel(tabla);
        RegistrarProducto registrarp = new RegistrarProducto();
        cantidad1.addActionListener(registrarp);
        registrar1.addActionListener(registrarp);
        DevolverProducto devolver = new DevolverProducto();
        devolver1.addActionListener(devolver);  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        identificacion1 = new javax.swing.JTextField();
        nombre1 = new javax.swing.JTextField();
        puntos1 = new javax.swing.JTextField();
        buscar1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        codigo1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Nombre1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Costo1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cantidad1 = new javax.swing.JTextField();
        registrar1 = new javax.swing.JButton();
        devolver1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        puntosactuales1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        informacion1 = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        total1 = new javax.swing.JTextField();
        registrarventa1 = new javax.swing.JButton();
        cancelarventa1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)), "Cliente"));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel13.setText("Identificación:");

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel14.setText("Nombre:");

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel15.setText("Puntos:");

        identificacion1.setBackground(new java.awt.Color(240, 240, 230));

        nombre1.setBackground(new java.awt.Color(240, 240, 230));
        nombre1.setEnabled(false);

        puntos1.setBackground(new java.awt.Color(240, 240, 230));
        puntos1.setEnabled(false);

        buscar1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        buscar1.setText("Buscar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(puntos1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(identificacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(identificacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buscar1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(puntos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255))));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel16.setText("Código:");

        codigo1.setBackground(new java.awt.Color(240, 240, 230));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel17.setText("Nombre:");

        Nombre1.setBackground(new java.awt.Color(240, 240, 230));
        Nombre1.setEnabled(false);

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel18.setText("Costo:");

        Costo1.setBackground(new java.awt.Color(240, 240, 230));
        Costo1.setEnabled(false);

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel19.setText("Cantidad:");

        cantidad1.setBackground(new java.awt.Color(240, 240, 230));

        registrar1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        registrar1.setText("REGISTRAR");

        devolver1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        devolver1.setText("DEVOLVER");
        devolver1.setEnabled(false);

        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel20.setText("Detalle de la Compra:");

        jLabel21.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel21.setText("Puntos Compra Actual:");

        puntosactuales1.setBackground(new java.awt.Color(240, 240, 230));

        informacion1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Costo Unitario", "Cantidad", "Costo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(informacion1);

        jLabel22.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel22.setText("TOTAL:");

        total1.setBackground(new java.awt.Color(240, 240, 230));

        registrarventa1.setText("Registrar Venta");

        cancelarventa1.setText("Cancelar Venta");

        jLabel23.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel23.setText("Vendedor:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(registrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(devolver1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Costo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(puntosactuales1))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addGap(18, 18, 18)
                                        .addComponent(total1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(registrarventa1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(cancelarventa1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Costo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrar1)
                    .addComponent(devolver1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(puntosactuales1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(total1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarventa1)
                    .addComponent(cancelarventa1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel23))
        );

        titulo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        titulo.setText("SUPERMERCADO CINDY CAICEDO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Costo1;
    private javax.swing.JTextField Nombre1;
    private javax.swing.JButton buscar1;
    private javax.swing.JButton cancelarventa1;
    private javax.swing.JTextField cantidad1;
    private javax.swing.JTextField codigo1;
    private javax.swing.JButton devolver1;
    private javax.swing.JTextField identificacion1;
    private javax.swing.JTable informacion1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombre1;
    private javax.swing.JTextField puntos1;
    private javax.swing.JTextField puntosactuales1;
    private javax.swing.JButton registrar1;
    private javax.swing.JButton registrarventa1;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField total1;
    // End of variables declaration//GEN-END:variables
public class BuscarCliente implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            try{
        String str = identificacion1.getText();
        long identificacion = Long.parseLong(str);
        Cliente cliente;
        cliente = almacen.buscarCliente(identificacion);
        nombre1.setText(cliente.getNombres());
       puntos1.setText(Short.toString((short) cliente.getPuntosAcumulados()));
       compra.setCliente(cliente);
        }catch(ObjectNotFoundException ex){
            JOptionPane.showMessageDialog(Grafica1.this, ex.getMessage());
            Logger.getLogger(Grafica1.class.getName()).log(Level.SEVERE,title);
        }catch(NumberFormatException exc){
           JOptionPane. showMessageDialog(Grafica1.this, "el numero de identificacion no esta");
          Logger.getLogger(Grafica1.class.getName()).log(Level.SEVERE,title);
        }    
}
}
/** es lo mismo que registrar producto
public class RegistrarDetalle implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            try{
           String cantidad = cantidad1.getText();
                   double quanty = Double.parseDouble(cantidad);
                   DetalleCompra detalle
                           = new DetalleCompra((int)quanty,producto);
                   compra.AgregarDetalle(detalle);
                   informacion1.updateUI();
                   codigo1.setText(producto.getCodigo());   
        } catch(NumberFormatException nfex){
        Logger.getLogger(Grafica1.class.getName()).log(Level.SEVERE, null,nfex);
}catch(Exception ex){
    Logger.getLogger(Grafica1.class.getName()).log(Level.SEVERE, null, ex);
}
    
}
 }
 */
public class BuscarProducto implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            try {
            String cod = codigo1.getText();
                producto = almacen.buscarProducto(cod);
                Nombre1.setText(producto.getNombre());
                Costo1.setText(producto.getCostoUnitario()+"");
                
            } catch (ObjectNotFoundException ex) {
                Logger.getLogger(Grafica1.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    
}
public class RegistrarProducto implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            int cant = Integer.parseInt(cantidad1.getText());
            DetalleCompra detalle;
            detalle = new DetalleCompra(cant, producto);
            compra.AgregarDetalle(detalle);
            informacion1.updateUI();
            codigo1.setText("");
            Nombre1.setText("");
            Costo1.setText("");
            producto = null;
            devolver1.setEnabled(true);
           }
    
}

public class SaleTableModel extends AbstractTableModel{

        @Override
        public int getRowCount() {
           return compra.getDetalleCompras().size();
        }

        @Override
        public int getColumnCount() {
            return 4;
        }

        @Override
        public String getColumnName(int columnIndex) {
           switch(columnIndex){
               case 0: return "Producto";
               case 1: return "Costo Unitario";
               case 2: return "Cantidad";
               case 3: return "Costo";
           }
           return"";
        }
        
        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            DetalleCompra detalle = compra.getDetalleCompras().get(rowIndex);
            switch(columnIndex){
                case 0 :return detalle.getProducto().getNombre();
                case 1: return "$" + detalle.getProducto().getCostoUnitario();
                case 2: return detalle.getCantProductos();
                case 3: return detalle.costoProducto();
            }
            return "";
             }
        }
public class DevolverProducto implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
         DetalleCompra detalle;
         int numero = informacion1.getSelectedRow();
          compra.Eliminar(numero);
          informacion1.updateUI();
        }
    
}
}
                
