
package Supermercado;

import Supermercado.Almacen;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
/**
 *
 * @author sony
 */
public class Grafica2 extends javax.swing.JFrame {

    private Almacen almacen;

    public Grafica2(Almacen almacen) {
        this.almacen = almacen;
        initComponents();
        this.AcercaDe.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(Grafica2.this, "Implementado por: Cindy Johana Caicedo");
            }
        });
        this.RealizarCompra.addActionListener(new ActionListener() {
            private Grafica1 grafic = null;

            @Override
            public void actionPerformed(ActionEvent e) {
                grafic = new Grafica1(almacen);
                Desktop.add(grafic);
                grafic.setVisible(true);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        Desktop = new javax.swing.JDesktopPane();
        MenuBar = new javax.swing.JMenuBar();
        aplicacion = new javax.swing.JMenu();
        IniciarSesion = new javax.swing.JMenuItem();
        CerrarSesion = new javax.swing.JMenuItem();
        MostrarVentas = new javax.swing.JMenuItem();
        RealizarCompra = new javax.swing.JMenuItem();
        ayuda = new javax.swing.JMenu();
        AcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        aplicacion.setText("APLICACIÓN");

        IniciarSesion.setText("Iniciar Sesion");
        aplicacion.add(IniciarSesion);

        CerrarSesion.setText("Cerrar Sesion");
        aplicacion.add(CerrarSesion);

        MostrarVentas.setText("Mostrar Ventas");
        aplicacion.add(MostrarVentas);

        RealizarCompra.setText("Realizar Compra");
        aplicacion.add(RealizarCompra);

        MenuBar.add(aplicacion);

        ayuda.setText("AYUDA");

        AcercaDe.setText("Acerca de");
        ayuda.add(AcercaDe);

        MenuBar.add(ayuda);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AcercaDe;
    private javax.swing.JMenuItem CerrarSesion;
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem IniciarSesion;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem MostrarVentas;
    private javax.swing.JMenuItem RealizarCompra;
    private javax.swing.JMenu aplicacion;
    private javax.swing.JMenu ayuda;
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables

}
